#!/usr/bin/env python3
"""Generate the payload-hash-only client index from the frozen QR catalog."""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
CATALOG_PATH = Path("shared/fixtures/qr/qr-cloud-fixture-catalog-v2.json")
MANIFEST_PATH = Path("shared/datasets/qr/manifest.json")
FIXTURE_NAMES = (
    "qr-cloud-analysis-v2-request.json",
    "qr-cloud-analysis-v2-status.json",
    "qr-cloud-analysis-v2-status-matrix.json",
    "qr-cloud-analysis-v2-errors.json",
)
GENERATED_DART = Path("mobile/lib/qr/qr_sample_index.g.dart")
ASSET_DIR = Path("mobile/assets/fixtures/qr")
SAMPLE_IDS = tuple(f"QR{i:02d}" for i in range(2, 14))


def _read_json(root: Path, path: Path) -> dict:
    return json.loads((root / path).read_text(encoding="utf-8"))


def build_index(root: Path = REPO_ROOT) -> dict[str, dict[str, str]]:
    catalog = _read_json(root, CATALOG_PATH)
    manifest = _read_json(root, MANIFEST_PATH)

    if catalog.get("schema_version") != "2.0":
        raise ValueError("Unsupported QR cloud catalog schema version")
    if catalog.get("catalog_revision") != "2026-10-09.1":
        raise ValueError("Unexpected QR cloud catalog revision")
    if catalog.get("analysis_mode") != "repository_fixture_static":
        raise ValueError("Unexpected QR fixture analysis mode")
    if catalog.get("source_manifest", {}).get("schema_version") != "1.0":
        raise ValueError("Unexpected source manifest schema version")

    manifest_cases = manifest.get("cases", []) + manifest.get(
        "supplemental_cases", []
    )
    manifest_by_id: dict[str, dict] = {}
    for case in manifest_cases:
        sample_id = case.get("id")
        if sample_id in manifest_by_id:
            raise ValueError(f"Duplicate QR manifest ID: {sample_id}")
        manifest_by_id[sample_id] = case

    catalog_cases = catalog.get("cases", []) + catalog.get(
        "supplemental_cases", []
    )
    catalog_by_id: dict[str, dict] = {}
    for case in catalog_cases:
        sample_id = case.get("id")
        if sample_id in catalog_by_id:
            raise ValueError(f"Duplicate QR catalog ID: {sample_id}")
        catalog_by_id[sample_id] = case

    expected = set(SAMPLE_IDS)
    if not expected.issubset(manifest_by_id):
        missing = sorted(expected - set(manifest_by_id))
        raise ValueError(f"Manifest is missing fixed samples: {missing}")
    if set(catalog_by_id) != expected:
        missing = sorted(expected - set(catalog_by_id))
        extra = sorted(set(catalog_by_id) - expected)
        raise ValueError(f"Catalog sample IDs differ; missing={missing}, extra={extra}")

    index: dict[str, dict[str, str]] = {}
    for sample_id in SAMPLE_IDS:
        manifest_case = manifest_by_id[sample_id]
        catalog_case = catalog_by_id[sample_id]
        payload = manifest_case.get("payload")
        if not isinstance(payload, str) or payload != catalog_case.get("payload"):
            raise ValueError(f"Canonical payload mismatch for {sample_id}")

        # Hash the exact UTF-8 bytes. Do not strip, decode, normalize, or case-fold.
        digest = hashlib.sha256(payload.encode("utf-8")).hexdigest()
        if digest != catalog_case.get("payload_sha256"):
            raise ValueError(f"Catalog payload hash mismatch for {sample_id}")
        if digest in index:
            raise ValueError(f"Duplicate payload hash for {sample_id}")

        index[digest] = {
            "sample_id": sample_id,
            "catalog_schema_version": catalog["schema_version"],
            "catalog_revision": catalog["catalog_revision"],
            "manifest_schema_version": catalog["source_manifest"]["schema_version"],
            "payload_sha256": digest,
            "analyzer_profile": catalog_case["analyzer_profile"],
        }
    return index


def render_dart(index: dict[str, dict[str, str]]) -> str:
    lines = [
        "// Generated by mobile/tool/generate_qr_sample_index.py. Do not edit.",
        "const Map<String, Map<String, String>> qrFixedSampleIndex = {",
    ]
    for digest, entry in index.items():
        fields = ", ".join(
            f"'{key}': '{value}'" for key, value in entry.items()
        )
        lines.append(f"  '{digest}': {{{fields}}},")
    lines.extend(["};", ""])
    return "\n".join(lines)


def synchronize_fixtures(root: Path, *, check: bool) -> None:
    source_dir = root / "shared/fixtures/qr"
    target_dir = root / ASSET_DIR
    if not check:
        target_dir.mkdir(parents=True, exist_ok=True)
    for name in FIXTURE_NAMES:
        source = source_dir / name
        target = target_dir / name
        if not source.is_file():
            raise ValueError(f"Missing B contract fixture: {source}")
        if check:
            if not target.is_file() or source.read_bytes() != target.read_bytes():
                raise ValueError(f"Bundled fixture is stale: {target}")
        else:
            shutil.copyfile(source, target)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    output = REPO_ROOT / GENERATED_DART
    expected = render_dart(build_index())
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != expected:
            raise SystemExit("Generated QR sample index is stale")
        synchronize_fixtures(REPO_ROOT, check=True)
        print("QR sample index and bundled B fixtures are current.")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8", newline="\n")
    synchronize_fixtures(REPO_ROOT, check=False)
    print(f"Generated {len(build_index())} QR sample hashes in {output}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
