User tinyproxy
Group tinyproxy
Port 8888
Listen 0.0.0.0
Timeout 90
LogFile "/tmp/tinyproxy.log"
LogLevel Info
PidFile "/tmp/tinyproxy.pid"
MaxClients 20
MinSpareServers 2
MaxSpareServers 5
StartServers 2
MaxRequestsPerChild 0
Allow 127.0.0.1
Allow 192.168.250.0/24
ConnectPort 443
